let ACCOUNT_TYPE;
let BUSINESS;
let ORDER_AMOUNT;
let DISCOUNT_RATE;
let TOTAL_AMOUNT;

ACCOUNT_TYPE = BUSINESS;
ORDER_AMOUNT = 900;
TOTAL_AMOUNT = 4000;

if (ACCOUNT_TYPE === BUSINESS) {
  if (ORDER_AMOUNT > 1000) {
    DISCOUNT_RATE = 10;
  } else {
    DISCOUNT_RATE = 5;
  }
} else {
  DISCOUNT_RATE = 0;
}

let DISCOUNT_AMOUNT = TOTAL_AMOUNT * DISCOUNT_RATE;
let AMOUNT_DUE = TOTAL_AMOUNT - DISCOUNT_AMOUNT;
console.log("\n");
console.log(TOTAL_AMOUNT, DISCOUNT_AMOUNT, AMOUNT_DUE);
console.log("\n");

// Result is 4000, 20000 and -16000
